root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

language: ja

redirects:
  /chapter1: /chapters/chapter1.md
  /chapter2: /chapters/chapter2.md
  /chapter3: /chapters/chapter3.md
  /glossary: /appendix/glossary.md
  /faq: /appendix/faq.md
